<?php
// $Id$

function user_relationship_privatemsg_form_alter($form_id, &$form) {
  global $user;

  switch ($form_id) {
  case 'privatemsg_new':
    $relationships = user_relationships_load(array('requester_id' => $user->uid));
    $contacts = array();
    foreach ($relationships as $relationship) {
      $contacts[$relationship->name][$relationship->requestee_name] = $relationship->requestee_name;
    }

    $form['quick']['#options'] = array_merge($form['quick']['#options'], $contacts);
    break;
  }
}
